//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScreenRuler.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EnumResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScreenRuler.Properties.EnumResources", typeof(EnumResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set marker(s) at current cursor position.
        /// </summary>
        internal static string Actions_AddMarkerAtCurrent {
            get {
                return ResourceManager.GetString("Actions_AddMarkerAtCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set marker at current length.
        /// </summary>
        internal static string Actions_AddMarkerAtLength {
            get {
                return ResourceManager.GetString("Actions_AddMarkerAtLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy current length to clipboard.
        /// </summary>
        internal static string Actions_CopySize {
            get {
                return ResourceManager.GetString("Actions_CopySize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrease ruler opacity.
        /// </summary>
        internal static string Actions_DecreaseOpacity {
            get {
                return ResourceManager.GetString("Actions_DecreaseOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove the first custom marker.
        /// </summary>
        internal static string Actions_DeleteFirstMarker {
            get {
                return ResourceManager.GetString("Actions_DeleteFirstMarker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase ruler opacity.
        /// </summary>
        internal static string Actions_IncreaseOpacity {
            get {
                return ResourceManager.GetString("Actions_IncreaseOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle hypotenuse display (in 2D).
        /// </summary>
        internal static string Actions_ToggleHypotenuseMode {
            get {
                return ResourceManager.GetString("Actions_ToggleHypotenuseMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle ruler orientation.
        /// </summary>
        internal static string Actions_ToggleRulerMode {
            get {
                return ResourceManager.GetString("Actions_ToggleRulerMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle slim scale.
        /// </summary>
        internal static string Actions_ToggleSlimMode {
            get {
                return ResourceManager.GetString("Actions_ToggleSlimMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle the ruler theme between light and dark.
        /// </summary>
        internal static string Actions_ToggleTheme {
            get {
                return ResourceManager.GetString("Actions_ToggleTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle vertical orientation.
        /// </summary>
        internal static string Actions_ToggleVertical {
            get {
                return ResourceManager.GetString("Actions_ToggleVertical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Centimeters.
        /// </summary>
        internal static string Centimeters {
            get {
                return ResourceManager.GetString("Centimeters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per-monitor automatic.
        /// </summary>
        internal static string DpiScalingMode_Auto {
            get {
                return ResourceManager.GetString("DpiScalingMode_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        internal static string DpiScalingMode_Manual {
            get {
                return ResourceManager.GetString("DpiScalingMode_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual (bidirectional).
        /// </summary>
        internal static string DpiScalingMode_ManualBidirectional {
            get {
                return ResourceManager.GetString("DpiScalingMode_ManualBidirectional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use scaled pixels.
        /// </summary>
        internal static string DpiScalingMode_Unaware {
            get {
                return ResourceManager.GetString("DpiScalingMode_Unaware", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At Ruler Length.
        /// </summary>
        internal static string HypotenuseMode_FixedAtLength {
            get {
                return ResourceManager.GetString("HypotenuseMode_FixedAtLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At Cursor Position.
        /// </summary>
        internal static string HypotenuseMode_Moving {
            get {
                return ResourceManager.GetString("HypotenuseMode_Moving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide.
        /// </summary>
        internal static string HypotenuseMode_None {
            get {
                return ResourceManager.GetString("HypotenuseMode_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inches.
        /// </summary>
        internal static string Inches {
            get {
                return ResourceManager.GetString("Inches", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percent.
        /// </summary>
        internal static string Percent {
            get {
                return ResourceManager.GetString("Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pixels.
        /// </summary>
        internal static string Pixels {
            get {
                return ResourceManager.GetString("Pixels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        internal static string Points {
            get {
                return ResourceManager.GetString("Points", resourceCulture);
            }
        }
    }
}
